name: Lint
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@dev
      - run: npm install
      - name: Lint
        run: npx eslint . 
        shell: bash